version: "3.3"

networks:
  # docker internal network
  lempnet:
    driver: bridge

services:

  # LEMP Server from image
  app:
    image: lemp-dev:v2
    container_name: drupalwebapp    
    env_file:
      - .env
    working_dir: /var/www/html/
    ports:
        - 80:80    
        - 443:443
        - 3306:3306        
    volumes:
      - ../www:/var/www/html/
    networks:
      - lempnet          
    tty: true


  # DB access via PHP my admin
  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
    image: corbinu/docker-phpmyadmin
    container_name: drupalwebapp-phpmyadmin
    environment:
      PMA_HOST: app
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_PORT_3306_TCP_ADDR: db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
    restart: always
    ports:
      - 8081:80
    networks:
      - lempnet          
